
project_id = "ijfkhyeljrxbkspgqewl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[functions.webhook-property]
verify_jwt = false

[functions.webhook-client]
verify_jwt = false

[functions.webhook-employee]
verify_jwt = false

[functions.webhook-lead]
verify_jwt = false

[functions.ai-reports]
verify_jwt = true
