// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijfkhyeljrxbkspgqewl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqZmtoeWVsanJ4YmtzcGdxZXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTMzNTYsImV4cCI6MjA2NDAyOTM1Nn0.siris3_IWy8y5SBLyJLCaU1jJqAO4kZXE40Za_eTur4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);